source 'https://rubygems.org'

gem 'sinatra'
gem 'simplecov'

group :development do
  gem 'bundle'
  gem 'capybara'
  gem 'minitest'
  gem 'rack-test'
  gem 'rake'
  gem 'rubocop'
  gem 'sinatra-contrib'
end